config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'welcome/index'
  get 'wikis/index'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end
  root 'welcome#index'

  resources :wikis do
    get "collaborators" => "collaborators#index"
    post "collaborator/:id" => "collaborators#create", as: 'add_collaborator'
    delete "collaborator/:id" => "collaborators#destroy", as: 'delete_collaborator'
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators, dependent: :destroy
  #has_many :collab_wikis, through: :collaborators, foreign_key: :user_id

  before_save { self.email = email.downcase }
  after_initialize { self.role ||= :member }

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:member, :premium, :admin]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      if @user.member?
        Wiki.publicize_user_wikis(@user)
        Collaborator.delete_user_wikis(@user)
      end
      flash[:notice] = 'User was updated successfully'
      redirect_to @user
    else
      flash.now[:alert] = 'There was an error saving the user. Please try again later.'
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :role)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: <%= @user.name %>-Edit</h1>
</div>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>

      <%= form_group_tag([]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', autofocus: true %>
      <% end %>

      <%= form_group_tag([]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control'%>
      <% end %>

      <% if @user.premium? %>
        <%= form_group_tag([]) do %>
          <%= f.label :role %><br />
          <%= f.label :role, :member %>
          <%= f.radio_button :role, :member %> |
          <%= f.label :role, :premium %>
          <%= f.radio_button :role, :premium, :checked => true %>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: <%= @user.name %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2"><h4>Name:</h4></div>
      <div class="col-md-5"><h4><%= current_user.name %></h4></div>
    </div>
    <div class="row">
      <div class="col-md-2"><h4>Email:</h4></div>
      <div class="col-md-2"><h4><%= current_user.email %></h4></div>
    </div>
    <div class="row">
      <div class="col-md-2"><h4>Account Type:</h4></div>
      <div class="col-md-5"><h4><%= current_user.role %></h4></div>
    </div>
  </div>
  <div class="panel-footer">
    <%= link_to "Edit", edit_user_path(@user), class: "btn btn-success" %>
    <% if @user.member? %>
      <%= link_to "Upgrade to Premium", new_charge_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>