config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'welcome/index'
  get 'wikis/index'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end
  root 'welcome#index'

  resources :wikis do
    get "collaborators" => "collaborators#index"
    post "collaborator/:id" => "collaborators#create", as: 'add_collaborator'
    delete "collaborator/:id" => "collaborators#destroy", as: 'delete_collaborator'
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  # def self.publicized_wiki(wiki)
  #   collabs = self.where(wiki: wiki)
  #   collabs.delete_all
  # end

  def self.delete_user_wikis(user)
    collabs = self.where(wiki: Wiki.where(user: user))
    collabs.delete_all
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  before_action :authenticate_user!

  def index
    @wiki = Wiki.find(params[:wiki_id])
    authorize @wiki, :collaborators?
    @users = policy_scope(Collaborator)
    puts @users
  end

  def create
    # @wiki = Wiki.find(params[:wiki_id])
    @collab = Collaborator.new(wiki_id: params[:wiki_id], user_id: params[:id])
    authorize @collab
    if @collab.save
      redirect_to :back
    else
      flash[:alert] = "Error creating collaborator. Please try again."
      redirect_to :back
    end
  end

  def destroy
    @collab = Collaborator.where(user_id: params[:id], wiki_id: params[:wiki_id]).first
    authorize @collab
    if @collab.destroy
      redirect_to :back
    else
      flash[:alert] = "There was an error deleting this collaborator. Please try again later."
      redirect_to :back
    end
  end


  private

  def collab_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper

  def is_collaborator (wiki, user)
    return wiki.collaborators.where(user: user).exists?
  end

  def get_collaborator (wiki, user)
    return wiki.collaborators.where(user: user).first
  end

end

app/views/collaborators/index.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: Wiki Collaborators</h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Wiki "<%= @wiki.title %>"</div>
  <div class="panel-body">
    <div class="list-group">
      <% @users.each do |user| %>
        <% if is_collaborator(@wiki, user) %>
          <%= link_to wiki_delete_collaborator_path(id: user.id), method: :delete, class: 'list-group-item list-group-item-success' do %>
            <span class="glyphicon glyphicon-minus pull-right"></span><%= user.name %>
          <% end %>
        <% else %>
          <%= link_to wiki_add_collaborator_path(id: user.id), method: :post, class: 'list-group-item' do %>
            <span class="glyphicon glyphicon-plus pull-right"></span><%= user.name %>
          <% end %>
        <% end %>
      <% end %>
    </div>

  </div>
  <div class="panel-footer">
    <%= link_to "Return to Wiki", wiki_path(@wiki), class: "btn btn-primary" %>
  </div>
</div>