config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'welcome/index'
  get 'wikis/index'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end
  root 'welcome#index'

  resources :wikis do
    get "collaborators" => "collaborators#index"
    post "collaborator/:id" => "collaborators#create", as: 'add_collaborator'
    delete "collaborator/:id" => "collaborators#destroy", as: 'delete_collaborator'
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: {minimum: 20 }, presence: true
  validates :user, presence: true

  def self.publicize_user_wikis(user)
    self.where(user: user).update_all(private: false)
  end

  #after_save { Collaborator.publicized_wiki(self) if !private }
  after_save { collaborators.destroy_all if !private }

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authenticate_user!
  # before_action :validate_user
  # before_action :authorize_user, except: [:index, :show, :new, :create]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    if @wiki.save
      # if !@wiki.private
      #   Collaborator.publicized_wiki(@wiki)
      # end
      flash[:notice] = 'Wiki was updated successfully'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error saving the wiki. Please try again later.'
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "Wiki deleted successfully"
      redirect_to wikis_index_path
    else
      flash.now[:alert] = "There was an error deleting this wiki. Please try again later."
      redirect_to wikis_index_path
    end
  end


  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end


  # def authorize_user
  #   wiki = Wiki.find(params[:id])
  #   unless current_user == wiki.user
  #     flash[:alert] = "You must own this wiki to do that."
  #     redirect_to wiki
  #   end
  # end

end

app/helpers/wikis_helper.rb
module WikisHelper

  def is_authorized_for_private()
    return !current_user.member?
  end

  def is_authorized_to_control(wiki)
    return wiki.user==current_user || current_user.admin?
  end

  def markdown(text)
    extensions = {
      fenced_code_blocks: true
    }
    renderer = Redcarpet::Render::HTML.new()
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end

end

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>

  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter wiki title' %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <div id="epiceditor">
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>
  <% end %>

  <% if is_authorized_for_private() %>
    <div class="form-group">
      <%= f.label :private %>
      <%= f.check_box :private %>
    </div>
  <% end %>

  <div class="form-group">
    <% if is_authorized_to_control(wiki) %>

      <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger' %>
    <% end %>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/wikis/_upgrade.html.erb
<% if user.member? %>
  <div class="jumbotron">
    <h3>Create your own private wikis for just $15 by upgrading to a premium account.</h3>
    <%= link_to "Let's Do It!", new_charge_path, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: Wikis-Edit</h1>
</div>

<%= render partial: 'upgrade', locals: { user: current_user } %>

<%= render partial: 'form', locals: { wiki: @wiki } %>

<%= javascript_tag do %>
  var opts = {
    theme: {
      preview: '/assets/preview/github',
      editor: '/assets/editor/epic-light'
    }
  }
  var editor = new EpicEditor(opts).load();
<% end %>

app/views/wikis/index.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: Wikis</h1>
</div>

<%= render partial: 'upgrade', locals: { user: current_user } %>

<div class="panel panel-default">
  <div class="panel-heading">Wikis</div>
  <div class="panel-body">
    <% @wikis.each do |wiki| %>
      <div style="margin-bottom: 10px" class="row">
        <div class="col-md-11">
          <%= link_to wiki, class: "btn btn-default btn-block"  do %>
            <div class="row">
              <% if wiki.private? %>
                <div class="col-sm-1">
                    <span class="glyphicon glyphicon-lock"></span>
                </div>
                <div class="col-sm-10">
                  <span class="pull-left"><%= wiki.title %></span>
                </div>
                <div class="col-sm-1">
                  <span class="glyphicon glyphicon-chevron-right pull-right"></span>
                </div>
              <% else %>
              <div class="col-sm-11">
                <span class="pull-left"><%= wiki.title %></span>
              </div>
              <div class="col-sm-1">
                <span class="glyphicon glyphicon-chevron-right pull-right"></span>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="col-md-1">
          <%= link_to edit_wiki_path(wiki), class: "btn btn-success btn-block" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div style="margin-top: -10px" class="panel-footer">
    <%= link_to "New Wiki", new_wiki_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: Wikis-New</h1>
</div>

<%= render partial: 'upgrade', locals: { user: current_user } %>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<div class="page-header">
  <h1 class="text-center">Blocipedia: Wikis-Show</h1>
</div>

<%= render partial: 'upgrade', locals: { user: current_user } %>

<div class="panel panel-default">
  <div class="panel-heading"><%= @wiki.title %></div>
  <div class="panel-body">
    <%= markdown(@wiki.body) %><br />
  </div>
  <div class="panel-footer">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-success" %>
    <% if is_authorized_to_control(@wiki) %>
      <%= link_to "Delete", @wiki, method: :delete, class: "btn btn-danger" %>
      <% if @wiki.private %>
        <%= link_to pluralize(@wiki.collaborators.count, "Collaborator"), wiki_collaborators_path(@wiki.id), class: 'btn btn-default' %>
      <% end %>
    <% end %>
    <span class="pull-right"><small>by <%= @wiki.user.name %></small></span>
  </div>
</div>