config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'welcome/index'
  get 'wikis/index'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end
  root 'welcome#index'

  resources :wikis do
    get "collaborators" => "collaborators#index"
    post "collaborator/:id" => "collaborators#create", as: 'add_collaborator'
    delete "collaborator/:id" => "collaborators#destroy", as: 'delete_collaborator'
  end



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li><%= link_to "Wikis", wikis_path %></li>
    </ul>
    <div style="padding-right:20px" class="navbar-right">
      <p class="navbar-text">
          <% if user_signed_in? %>
              <%= link_to current_user.name, user_path(current_user) %>
               | <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
             <%= link_to "Sign In", new_user_session_path %> |
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
       </p>
    </div>
  </nav>

  <div class="container row">
    <div class="flash">
       <% if flash[:notice] %>
         <div class="alert alert-success">
             <button type="button" class="close" data-dismiss='alert'>&times;</button>
             <%= flash[:notice] %>
           </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss='alert'>&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss='alert'>&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
    </div>
  </div>

  <%= yield %>

</div>

</body>
</html>